Add support for extra sources
next-actions/build-srpm pull request #1
Opened 2023-08-01 18:37 UTC by justin-stephenson

2023-08-01 18:39 UTC, justin-stephenson commented
`Test / action (pull_request)` failing due to `next-actions/build-srpm@master` in workflow file

2023-08-02 07:28 UTC, ikerexxe commented
Is a tarball the easiest way to add a bunch of files in rpm generation?

2023-08-02 11:44 UTC, pbrezina commented
I agree, it would be nice to be able to just specify the file. If we can't pass list of files (I hope we can) we can use some separator.

2023-08-02 11:45 UTC, pbrezina commented
> `Test / action (pull_request)` failing due to `next-actions/build-srpm@master` in workflow file

I think you can modify it to call the action from checkouted repository instead from tag. E.g. https://github.com/next-actions/copr/blob/master/.github/workflows/test.yml#L83

2023-08-02 12:56 UTC, justin-stephenson commented
> I agree, it would be nice to be able to just specify the file. If we can't pass list of files (I hope we can) we can use some separator.

I couldn't see how to pass a list of files, so I went with the tarball approach. Can you expand on `we can use some separator` ?

2023-08-03 11:55 UTC, pbrezina commented
See `files` in https://github.com/next-actions/print-logs#example-usage for example.

Code: https://github.com/next-actions/print-logs/blob/master/action.yml#L21

2023-08-03 14:03 UTC, justin-stephenson commented
> > `Test / action (pull_request)` failing due to `next-actions/build-srpm@master` in workflow file
> 
> I think you can modify it to call the action from checkouted repository instead from tag. E.g. https://github.com/next-actions/copr/blob/master/.github/workflows/test.yml#L83

Thanks, I added a separate commit to make this change.

2023-08-03 14:03 UTC, justin-stephenson commented
> See `files` in https://github.com/next-actions/print-logs#example-usage for example.
> 
> Code: https://github.com/next-actions/print-logs/blob/master/action.yml#L21

Done, please check.

2023-08-03 14:33 UTC, ikerexxe approved these changes
The new version certainly looks better. Thanks for taking care of it.

2023-08-03 17:58 UTC, pbrezina commented
LGTM, can you also extend the PR CI check to list files inside src.rpm and check that all source are there?

2023-08-07 13:44 UTC, justin-stephenson commented
> LGTM, can you also extend the PR CI check to list files inside src.rpm and check that all source are there?

PR updated.

2023-08-07 13:50 UTC, pbrezina requested changes
Thank you. Last nitpick and let's merge it.

2023-08-07 13:50 UTC, pbrezina commented on .github/workflows/test.yml
> +          readme2.md
Can you put this to the example in the readme file? After that, feel free to merge it.

2023-08-07 13:56 UTC, justin-stephenson commented on .github/workflows/test.yml
> +          readme2.md
Done. I don't have merge access

2023-08-07 13:59 UTC, merged